title: York Student Homes
description: A great place to find a great place to live!
host: 0.0.0.0

url: https://yorkstudenthomes.com
baseurl: ""
repository: yorkstudenthomes/yorkstudenthomes.com
permalink: /:title/

timezone: Europe/London
locale: en-GB

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - netlify.toml
  - TODO
  - vendor

plugins:
  - jekyll-redirect-from

sass:
  style: compressed

defaults:
  - scope:
      type: pages
    values:
      og_type: website
  - scope:
      type: homes
    values:
      layout: home

collections:
  homes:
    output: true
    permalink: /homes/:name/

meta:
  description: York Student Homes - providing 4–6-bedroom houses to students in York for over 20 years.
  keywords:
    - york student homes
    - york student houses
    - accommodation
    - living
    - renting
    - homes
    - houses
    - properties
    - aparments
    - living
    - students
    - york

epc:
  eer: Energy Efficiency Rating
  eir: Environmental (CO₂) Impact Rating
