name: Build
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_app_name: yorkstudenthomes
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
        env:
          HD_YSH_ADMIN_PASSWORDS: ${{ secrets.YSH_ADMIN_PASSWORDS }}
