name: Update Config
on:
  workflow_dispatch:
    inputs:
      user:
        description: User that performed the update
        required: true
      contents:
        description: File contents
        required: true
      home-id:
        description: Home ID
jobs:
  commit-contents:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: ${{ github.ref }}
      - name: Get file name
        id: get-file
        env:
          HOME_ID: ${{ github.event.inputs.home-id }}
        run: |
          [ -n "$HOME_ID" ] && echo "::set-output name=file::_homes/$HOME_ID.md"
          [ -z "$HOME_ID" ] && echo "::set-output name=file::_data/config.yml"
      - uses: DamianReeves/write-file-action@v1.0
        with:
          path: ${{ github.workspace }}/${{ steps.get-file.outputs.file }}
          contents: ${{ github.event.inputs.contents }}
      - name: Commit changes
        env:
          USER_NAME: ${{ github.event.inputs.user }}
        run: |
          git config user.name "$USER_NAME"
          git config user.email "$USER_NAME@yorkstudenthomes.com"
          git commit -am 'Update config from admin'
          git push
